kind: Deployment
apiVersion: apps/v1
metadata:
  name: unbind-auth-deployment
  namespace: unbind
  labels:
    app: unbind-auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: unbind-auth
  template:
    metadata:
      labels:
        app: unbind-auth
    spec:
      containers:
        - name: unbind-auth
          image: replaceme
          command: ["/app/oauth2server"]
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              memory: 2Gi
              cpu: 500m
          ports:
            - containerPort: 8090
          imagePullPolicy: "Always"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: unbind-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unbind-db-credentials
                  key: password
          envFrom:
            - secretRef:
                name: unbind-api
