with-expecter: true
packages:
  github.com/unbindapp/unbind-api/internal/repository:
    config:
      dir: ./mocks/repository
    interfaces:
      BaseRepositoryInterface:
        config:
          filename: base_repository_mock.go
          mockName: BaseRepositoryMock
          outpkg: mocks_repository
      TxInterface:
        config:
          dir: ./mocks/repository/tx
          filename: tx_mock.go
          mockName: TxMock
          outpkg: mocks_repository_tx
  github.com/unbindapp/unbind-api/internal/repository/github:
    config:
      dir: ./mocks/repository/github
    interfaces:
      GithubRepositoryInterface:
        config:
          filename: github_repository_mock.go
          mockName: GithubRepositoryMock
          outpkg: mocks_repository_github
  github.com/unbindapp/unbind-api/internal/repository/user:
    config:
      dir: ./mocks/repository/user
    interfaces:
      UserRepositoryInterface:
        config:
          filename: user_repository_mock.go
          mockName: UserRepositoryMock
          outpkg: mocks_repository_user
  github.com/unbindapp/unbind-api/internal/repository/oauth:
    config:
      dir: ./mocks/repository/oauth
    interfaces:
      OauthRepositoryInterface:
        config:
          filename: oauth_repository_mock.go
          mockName: OauthRepositoryMock
          outpkg: mocks_repository_oauth
  github.com/unbindapp/unbind-api/internal/database/repositories:
    config:
      dir: ./mocks/repositories
    interfaces:
      RepositoriesInterface:
        config:
          filename: repositories_mock.go
          mockName: RepositoriesMock
          outpkg: mocks_repositories