# Docker file for github actions CI build
FROM stablecog/ubuntu:22.04

COPY ./internal/oauth2server/template/* /app/template/
COPY ./cmd/api /app/api
COPY ./cmd/oauth2server /app/oauth2server

EXPOSE 8080

CMD ["/app/server"]