apiVersion: v1
kind: ServiceAccount
metadata:
  name: unbind-api-sa
  namespace: unbind-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unbind-api-rbac
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: ["", "apps", "batch", "extensions", "networking.k8s.io", "apiextensions.k8s.io"]
  resources: [
    "namespaces",
    "configmaps", 
    "secrets", 
    "pods", 
    "services", 
    "deployments", 
    "statefulsets", 
    "replicasets", 
    "daemonsets", 
    "jobs", 
    "cronjobs", 
    "ingresses", 
    "ingressclasses", 
    "networkpolicies", 
    "persistentvolumeclaims", 
    "endpoints", 
    "events", 
    "customresourcedefinitions"
  ]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unbind-api-rbac-binding
roleRef:
  kind: ClusterRole
  name: unbind-api-rbac
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: unbind-api-sa
  namespace: unbind-system
