# ! TODO - We need to fix this so that unbind-api doesn't have a superuser clusterrole
# ! We will need to be able to manage secrets in team namespaces
# ! We will need to be able to create Role and Rolebindings in general in team namespaces.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unbind-api-sa
  namespace: unbind-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unbind-api-rbac
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: ["", "apps", "batch", "extensions", "networking.k8s.io", "apiextensions.k8s.io"]
  resources: [
    "namespaces",
    "configmaps", 
    "secrets", 
    "pods", 
    "services", 
    "deployments", 
    "statefulsets", 
    "replicasets", 
    "daemonsets", 
    "jobs", 
    "cronjobs", 
    "ingresses", 
    "ingressclasses", 
    "networkpolicies", 
    "persistentvolumeclaims", 
    "endpoints", 
    "events", 
    "customresourcedefinitions"
  ]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Custom operator CRD resources
# ! TODO - we can also make this one related to user tokens like some of the other roles
- apiGroups: ["unbind.unbind.app"]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unbind-api-rbac-binding
roleRef:
  kind: ClusterRole
  name: unbind-api-rbac
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: unbind-api-sa
  namespace: unbind-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager
  namespace: unbind-system
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding
  namespace: unbind-system
subjects:
  - kind: ServiceAccount
    name: unbind-api-sa
    namespace: unbind-system
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io