package templates

import (
	"github.com/unbindapp/unbind-api/ent/schema"
	"github.com/unbindapp/unbind-api/internal/common/utils"
	corev1 "k8s.io/api/core/v1"
)

// WireGuardTemplate returns the predefined WireGuard template
func wireGuardTemplate() *schema.TemplateDefinition {
	return &schema.TemplateDefinition{
		Name:        "wireguard",
		Version:     1,
		Description: "WireGuard VPN with web-based management interface",
		Inputs: []schema.TemplateInput{
			{
				ID:          1,
				Name:        "Host",
				Type:        schema.InputTypeHost,
				Description: "Hostname to use for the WireGuard instance.",
				Required:    true,
				TargetPort:  utils.ToPtr(51821),
			},
			{
				ID:          2,
				Name:        "UDP Port",
				Type:        schema.InputTypeNodePort,
				Description: "UDP port to use for the WireGuard instance, generated by default.",
				Required:    true,
			},
			{
				ID:          3,
				Name:        "Storage Size",
				Type:        schema.InputTypeVolumeSize,
				Description: "Size of the persistent storage for Wireguard config data.",
				Required:    true,
				Default:     utils.ToPtr("1Gi"),
			},
		},
		Services: []schema.TemplateService{
			{
				ID:           1,
				Name:         "WireGuard",
				Type:         schema.ServiceTypeDockerimage,
				Builder:      schema.ServiceBuilderDocker,
				HostInputIDs: []int{1},
				Image:        utils.ToPtr("ghcr.io/wg-easy/wg-easy:14"),
				Ports: []schema.PortSpec{
					{
						InputTemplateID: utils.ToPtr(2),
						IsNodePort:      true,
						Protocol:        utils.ToPtr(schema.ProtocolUDP),
					},
					{
						Port:     51821,
						Protocol: utils.ToPtr(schema.ProtocolTCP),
					},
				},
				IsPublic: true,
				Variables: []schema.TemplateVariable{
					{
						Name: "WG_HOST",
						Generator: &schema.ValueGenerator{
							Type:    schema.GeneratorTypeInput,
							InputID: 1,
						},
					},
					{
						Name: "WG_PORT",
						Generator: &schema.ValueGenerator{
							Type:    schema.GeneratorTypeInput,
							InputID: 2,
						},
					},
					{
						Name:  "LANG",
						Value: "en",
					},
					{
						Name:  "WG_DEFAULT_DNS",
						Value: "1.1.1.1",
					},
					{
						Name:  "WG_MTU",
						Value: "1420",
					},
					{
						Name:  "UI_TRAFFIC_STATS",
						Value: "true",
					},
					{
						Name:  "UI_CHART_TYPE",
						Value: "1",
					},
				},
				Volumes: []schema.TemplateVolume{
					{
						Name: "wireguard-config",
						Size: schema.TemplateVolumeSize{
							FromInputID: 3,
						},
						MountPath: "/etc/wireguard",
					},
				},
				SecurityContext: &schema.SecurityContext{
					SecurityContext: &corev1.SecurityContext{
						Privileged: utils.ToPtr(true),
						Capabilities: &corev1.Capabilities{
							Add: []corev1.Capability{
								"NET_ADMIN",
								"SYS_MODULE",
							},
						},
					},
				},
			},
		},
	}
}
