// Code generated by ifacemaker; DO NOT EDIT.

package system_repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/unbindapp/unbind-api/ent"
)

// SystemRepositoryInterface ...
type SystemRepositoryInterface interface {
	GetBuildkitSettings(ctx context.Context) (*ent.BuildkitSettings, error)
	CreateBuildkitSettings(ctx context.Context, replicas int, parallelism int) (*ent.BuildkitSettings, error)
	UpdateBuildkitSettings(ctx context.Context, id uuid.UUID, replicas int, parallelism int) (*ent.BuildkitSettings, error)
}
