// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/unbindapp/unbind-api/ent/environment"
	"github.com/unbindapp/unbind-api/ent/project"
	"github.com/unbindapp/unbind-api/ent/service"
	"github.com/unbindapp/unbind-api/ent/servicegroup"
)

// EnvironmentCreate is the builder for creating a Environment entity.
type EnvironmentCreate struct {
	config
	mutation *EnvironmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (ec *EnvironmentCreate) SetCreatedAt(t time.Time) *EnvironmentCreate {
	ec.mutation.SetCreatedAt(t)
	return ec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ec *EnvironmentCreate) SetNillableCreatedAt(t *time.Time) *EnvironmentCreate {
	if t != nil {
		ec.SetCreatedAt(*t)
	}
	return ec
}

// SetUpdatedAt sets the "updated_at" field.
func (ec *EnvironmentCreate) SetUpdatedAt(t time.Time) *EnvironmentCreate {
	ec.mutation.SetUpdatedAt(t)
	return ec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ec *EnvironmentCreate) SetNillableUpdatedAt(t *time.Time) *EnvironmentCreate {
	if t != nil {
		ec.SetUpdatedAt(*t)
	}
	return ec
}

// SetKubernetesName sets the "kubernetes_name" field.
func (ec *EnvironmentCreate) SetKubernetesName(s string) *EnvironmentCreate {
	ec.mutation.SetKubernetesName(s)
	return ec
}

// SetName sets the "name" field.
func (ec *EnvironmentCreate) SetName(s string) *EnvironmentCreate {
	ec.mutation.SetName(s)
	return ec
}

// SetDescription sets the "description" field.
func (ec *EnvironmentCreate) SetDescription(s string) *EnvironmentCreate {
	ec.mutation.SetDescription(s)
	return ec
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ec *EnvironmentCreate) SetNillableDescription(s *string) *EnvironmentCreate {
	if s != nil {
		ec.SetDescription(*s)
	}
	return ec
}

// SetActive sets the "active" field.
func (ec *EnvironmentCreate) SetActive(b bool) *EnvironmentCreate {
	ec.mutation.SetActive(b)
	return ec
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (ec *EnvironmentCreate) SetNillableActive(b *bool) *EnvironmentCreate {
	if b != nil {
		ec.SetActive(*b)
	}
	return ec
}

// SetProjectID sets the "project_id" field.
func (ec *EnvironmentCreate) SetProjectID(u uuid.UUID) *EnvironmentCreate {
	ec.mutation.SetProjectID(u)
	return ec
}

// SetKubernetesSecret sets the "kubernetes_secret" field.
func (ec *EnvironmentCreate) SetKubernetesSecret(s string) *EnvironmentCreate {
	ec.mutation.SetKubernetesSecret(s)
	return ec
}

// SetID sets the "id" field.
func (ec *EnvironmentCreate) SetID(u uuid.UUID) *EnvironmentCreate {
	ec.mutation.SetID(u)
	return ec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ec *EnvironmentCreate) SetNillableID(u *uuid.UUID) *EnvironmentCreate {
	if u != nil {
		ec.SetID(*u)
	}
	return ec
}

// SetProject sets the "project" edge to the Project entity.
func (ec *EnvironmentCreate) SetProject(p *Project) *EnvironmentCreate {
	return ec.SetProjectID(p.ID)
}

// AddServiceIDs adds the "services" edge to the Service entity by IDs.
func (ec *EnvironmentCreate) AddServiceIDs(ids ...uuid.UUID) *EnvironmentCreate {
	ec.mutation.AddServiceIDs(ids...)
	return ec
}

// AddServices adds the "services" edges to the Service entity.
func (ec *EnvironmentCreate) AddServices(s ...*Service) *EnvironmentCreate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return ec.AddServiceIDs(ids...)
}

// AddProjectDefaultIDs adds the "project_default" edge to the Project entity by IDs.
func (ec *EnvironmentCreate) AddProjectDefaultIDs(ids ...uuid.UUID) *EnvironmentCreate {
	ec.mutation.AddProjectDefaultIDs(ids...)
	return ec
}

// AddProjectDefault adds the "project_default" edges to the Project entity.
func (ec *EnvironmentCreate) AddProjectDefault(p ...*Project) *EnvironmentCreate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ec.AddProjectDefaultIDs(ids...)
}

// AddServiceGroupIDs adds the "service_groups" edge to the ServiceGroup entity by IDs.
func (ec *EnvironmentCreate) AddServiceGroupIDs(ids ...uuid.UUID) *EnvironmentCreate {
	ec.mutation.AddServiceGroupIDs(ids...)
	return ec
}

// AddServiceGroups adds the "service_groups" edges to the ServiceGroup entity.
func (ec *EnvironmentCreate) AddServiceGroups(s ...*ServiceGroup) *EnvironmentCreate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return ec.AddServiceGroupIDs(ids...)
}

// Mutation returns the EnvironmentMutation object of the builder.
func (ec *EnvironmentCreate) Mutation() *EnvironmentMutation {
	return ec.mutation
}

// Save creates the Environment in the database.
func (ec *EnvironmentCreate) Save(ctx context.Context) (*Environment, error) {
	ec.defaults()
	return withHooks(ctx, ec.sqlSave, ec.mutation, ec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EnvironmentCreate) SaveX(ctx context.Context) *Environment {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EnvironmentCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EnvironmentCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ec *EnvironmentCreate) defaults() {
	if _, ok := ec.mutation.CreatedAt(); !ok {
		v := environment.DefaultCreatedAt()
		ec.mutation.SetCreatedAt(v)
	}
	if _, ok := ec.mutation.UpdatedAt(); !ok {
		v := environment.DefaultUpdatedAt()
		ec.mutation.SetUpdatedAt(v)
	}
	if _, ok := ec.mutation.Active(); !ok {
		v := environment.DefaultActive
		ec.mutation.SetActive(v)
	}
	if _, ok := ec.mutation.ID(); !ok {
		v := environment.DefaultID()
		ec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *EnvironmentCreate) check() error {
	if _, ok := ec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Environment.created_at"`)}
	}
	if _, ok := ec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Environment.updated_at"`)}
	}
	if _, ok := ec.mutation.KubernetesName(); !ok {
		return &ValidationError{Name: "kubernetes_name", err: errors.New(`ent: missing required field "Environment.kubernetes_name"`)}
	}
	if v, ok := ec.mutation.KubernetesName(); ok {
		if err := environment.KubernetesNameValidator(v); err != nil {
			return &ValidationError{Name: "kubernetes_name", err: fmt.Errorf(`ent: validator failed for field "Environment.kubernetes_name": %w`, err)}
		}
	}
	if _, ok := ec.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Environment.name"`)}
	}
	if _, ok := ec.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Environment.active"`)}
	}
	if _, ok := ec.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Environment.project_id"`)}
	}
	if _, ok := ec.mutation.KubernetesSecret(); !ok {
		return &ValidationError{Name: "kubernetes_secret", err: errors.New(`ent: missing required field "Environment.kubernetes_secret"`)}
	}
	if len(ec.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Environment.project"`)}
	}
	return nil
}

func (ec *EnvironmentCreate) sqlSave(ctx context.Context) (*Environment, error) {
	if err := ec.check(); err != nil {
		return nil, err
	}
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ec.mutation.id = &_node.ID
	ec.mutation.done = true
	return _node, nil
}

func (ec *EnvironmentCreate) createSpec() (*Environment, *sqlgraph.CreateSpec) {
	var (
		_node = &Environment{config: ec.config}
		_spec = sqlgraph.NewCreateSpec(environment.Table, sqlgraph.NewFieldSpec(environment.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = ec.conflict
	if id, ok := ec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ec.mutation.CreatedAt(); ok {
		_spec.SetField(environment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ec.mutation.UpdatedAt(); ok {
		_spec.SetField(environment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ec.mutation.KubernetesName(); ok {
		_spec.SetField(environment.FieldKubernetesName, field.TypeString, value)
		_node.KubernetesName = value
	}
	if value, ok := ec.mutation.Name(); ok {
		_spec.SetField(environment.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ec.mutation.Description(); ok {
		_spec.SetField(environment.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := ec.mutation.Active(); ok {
		_spec.SetField(environment.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := ec.mutation.KubernetesSecret(); ok {
		_spec.SetField(environment.FieldKubernetesSecret, field.TypeString, value)
		_node.KubernetesSecret = value
	}
	if nodes := ec.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ProjectTable,
			Columns: []string{environment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ec.mutation.ServicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServicesTable,
			Columns: []string{environment.ServicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ec.mutation.ProjectDefaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ProjectDefaultTable,
			Columns: []string{environment.ProjectDefaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ec.mutation.ServiceGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.ServiceGroupsTable,
			Columns: []string{environment.ServiceGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicegroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Environment.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnvironmentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ec *EnvironmentCreate) OnConflict(opts ...sql.ConflictOption) *EnvironmentUpsertOne {
	ec.conflict = opts
	return &EnvironmentUpsertOne{
		create: ec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Environment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ec *EnvironmentCreate) OnConflictColumns(columns ...string) *EnvironmentUpsertOne {
	ec.conflict = append(ec.conflict, sql.ConflictColumns(columns...))
	return &EnvironmentUpsertOne{
		create: ec,
	}
}

type (
	// EnvironmentUpsertOne is the builder for "upsert"-ing
	//  one Environment node.
	EnvironmentUpsertOne struct {
		create *EnvironmentCreate
	}

	// EnvironmentUpsert is the "OnConflict" setter.
	EnvironmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EnvironmentUpsert) SetUpdatedAt(v time.Time) *EnvironmentUpsert {
	u.Set(environment.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnvironmentUpsert) UpdateUpdatedAt() *EnvironmentUpsert {
	u.SetExcluded(environment.FieldUpdatedAt)
	return u
}

// SetKubernetesName sets the "kubernetes_name" field.
func (u *EnvironmentUpsert) SetKubernetesName(v string) *EnvironmentUpsert {
	u.Set(environment.FieldKubernetesName, v)
	return u
}

// UpdateKubernetesName sets the "kubernetes_name" field to the value that was provided on create.
func (u *EnvironmentUpsert) UpdateKubernetesName() *EnvironmentUpsert {
	u.SetExcluded(environment.FieldKubernetesName)
	return u
}

// SetName sets the "name" field.
func (u *EnvironmentUpsert) SetName(v string) *EnvironmentUpsert {
	u.Set(environment.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnvironmentUpsert) UpdateName() *EnvironmentUpsert {
	u.SetExcluded(environment.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *EnvironmentUpsert) SetDescription(v string) *EnvironmentUpsert {
	u.Set(environment.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *EnvironmentUpsert) UpdateDescription() *EnvironmentUpsert {
	u.SetExcluded(environment.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *EnvironmentUpsert) ClearDescription() *EnvironmentUpsert {
	u.SetNull(environment.FieldDescription)
	return u
}

// SetActive sets the "active" field.
func (u *EnvironmentUpsert) SetActive(v bool) *EnvironmentUpsert {
	u.Set(environment.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *EnvironmentUpsert) UpdateActive() *EnvironmentUpsert {
	u.SetExcluded(environment.FieldActive)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *EnvironmentUpsert) SetProjectID(v uuid.UUID) *EnvironmentUpsert {
	u.Set(environment.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *EnvironmentUpsert) UpdateProjectID() *EnvironmentUpsert {
	u.SetExcluded(environment.FieldProjectID)
	return u
}

// SetKubernetesSecret sets the "kubernetes_secret" field.
func (u *EnvironmentUpsert) SetKubernetesSecret(v string) *EnvironmentUpsert {
	u.Set(environment.FieldKubernetesSecret, v)
	return u
}

// UpdateKubernetesSecret sets the "kubernetes_secret" field to the value that was provided on create.
func (u *EnvironmentUpsert) UpdateKubernetesSecret() *EnvironmentUpsert {
	u.SetExcluded(environment.FieldKubernetesSecret)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Environment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(environment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EnvironmentUpsertOne) UpdateNewValues() *EnvironmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(environment.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(environment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Environment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnvironmentUpsertOne) Ignore() *EnvironmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnvironmentUpsertOne) DoNothing() *EnvironmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnvironmentCreate.OnConflict
// documentation for more info.
func (u *EnvironmentUpsertOne) Update(set func(*EnvironmentUpsert)) *EnvironmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnvironmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnvironmentUpsertOne) SetUpdatedAt(v time.Time) *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnvironmentUpsertOne) UpdateUpdatedAt() *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKubernetesName sets the "kubernetes_name" field.
func (u *EnvironmentUpsertOne) SetKubernetesName(v string) *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetKubernetesName(v)
	})
}

// UpdateKubernetesName sets the "kubernetes_name" field to the value that was provided on create.
func (u *EnvironmentUpsertOne) UpdateKubernetesName() *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateKubernetesName()
	})
}

// SetName sets the "name" field.
func (u *EnvironmentUpsertOne) SetName(v string) *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnvironmentUpsertOne) UpdateName() *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *EnvironmentUpsertOne) SetDescription(v string) *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *EnvironmentUpsertOne) UpdateDescription() *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *EnvironmentUpsertOne) ClearDescription() *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.ClearDescription()
	})
}

// SetActive sets the "active" field.
func (u *EnvironmentUpsertOne) SetActive(v bool) *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *EnvironmentUpsertOne) UpdateActive() *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateActive()
	})
}

// SetProjectID sets the "project_id" field.
func (u *EnvironmentUpsertOne) SetProjectID(v uuid.UUID) *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *EnvironmentUpsertOne) UpdateProjectID() *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateProjectID()
	})
}

// SetKubernetesSecret sets the "kubernetes_secret" field.
func (u *EnvironmentUpsertOne) SetKubernetesSecret(v string) *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetKubernetesSecret(v)
	})
}

// UpdateKubernetesSecret sets the "kubernetes_secret" field to the value that was provided on create.
func (u *EnvironmentUpsertOne) UpdateKubernetesSecret() *EnvironmentUpsertOne {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateKubernetesSecret()
	})
}

// Exec executes the query.
func (u *EnvironmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnvironmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnvironmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnvironmentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: EnvironmentUpsertOne.ID is not supported by MySQL driver. Use EnvironmentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnvironmentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EnvironmentCreateBulk is the builder for creating many Environment entities in bulk.
type EnvironmentCreateBulk struct {
	config
	err      error
	builders []*EnvironmentCreate
	conflict []sql.ConflictOption
}

// Save creates the Environment entities in the database.
func (ecb *EnvironmentCreateBulk) Save(ctx context.Context) ([]*Environment, error) {
	if ecb.err != nil {
		return nil, ecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Environment, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnvironmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ecb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EnvironmentCreateBulk) SaveX(ctx context.Context) []*Environment {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EnvironmentCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EnvironmentCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Environment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnvironmentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ecb *EnvironmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnvironmentUpsertBulk {
	ecb.conflict = opts
	return &EnvironmentUpsertBulk{
		create: ecb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Environment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ecb *EnvironmentCreateBulk) OnConflictColumns(columns ...string) *EnvironmentUpsertBulk {
	ecb.conflict = append(ecb.conflict, sql.ConflictColumns(columns...))
	return &EnvironmentUpsertBulk{
		create: ecb,
	}
}

// EnvironmentUpsertBulk is the builder for "upsert"-ing
// a bulk of Environment nodes.
type EnvironmentUpsertBulk struct {
	create *EnvironmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Environment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(environment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EnvironmentUpsertBulk) UpdateNewValues() *EnvironmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(environment.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(environment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Environment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnvironmentUpsertBulk) Ignore() *EnvironmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnvironmentUpsertBulk) DoNothing() *EnvironmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnvironmentCreateBulk.OnConflict
// documentation for more info.
func (u *EnvironmentUpsertBulk) Update(set func(*EnvironmentUpsert)) *EnvironmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnvironmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnvironmentUpsertBulk) SetUpdatedAt(v time.Time) *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnvironmentUpsertBulk) UpdateUpdatedAt() *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKubernetesName sets the "kubernetes_name" field.
func (u *EnvironmentUpsertBulk) SetKubernetesName(v string) *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetKubernetesName(v)
	})
}

// UpdateKubernetesName sets the "kubernetes_name" field to the value that was provided on create.
func (u *EnvironmentUpsertBulk) UpdateKubernetesName() *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateKubernetesName()
	})
}

// SetName sets the "name" field.
func (u *EnvironmentUpsertBulk) SetName(v string) *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnvironmentUpsertBulk) UpdateName() *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *EnvironmentUpsertBulk) SetDescription(v string) *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *EnvironmentUpsertBulk) UpdateDescription() *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *EnvironmentUpsertBulk) ClearDescription() *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.ClearDescription()
	})
}

// SetActive sets the "active" field.
func (u *EnvironmentUpsertBulk) SetActive(v bool) *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *EnvironmentUpsertBulk) UpdateActive() *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateActive()
	})
}

// SetProjectID sets the "project_id" field.
func (u *EnvironmentUpsertBulk) SetProjectID(v uuid.UUID) *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *EnvironmentUpsertBulk) UpdateProjectID() *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateProjectID()
	})
}

// SetKubernetesSecret sets the "kubernetes_secret" field.
func (u *EnvironmentUpsertBulk) SetKubernetesSecret(v string) *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.SetKubernetesSecret(v)
	})
}

// UpdateKubernetesSecret sets the "kubernetes_secret" field to the value that was provided on create.
func (u *EnvironmentUpsertBulk) UpdateKubernetesSecret() *EnvironmentUpsertBulk {
	return u.Update(func(s *EnvironmentUpsert) {
		s.UpdateKubernetesSecret()
	})
}

// Exec executes the query.
func (u *EnvironmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnvironmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnvironmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnvironmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
